version: '3'
services:
  app:
    build: .
    restart: always
    image: finaltask:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: 12345
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: localspringbootdb
      
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: